#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# 博客上线向导：建仓 → push → Pages → Giscus。请在仓库根目录运行：
#   bash scripts/github-setup-wizard.sh

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready, set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: 博客上线 GitHub Pages（8 阶段，可随时 Ctrl-C 中断后重跑）
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "博客上线 GitHub Pages"

# 守卫：必须在仓库根目录运行（能看到两个配置文件才算）
if [[ ! -f _config.yml || ! -f _config.butterfly.yml ]]; then
  warn "未找到 _config.yml / _config.butterfly.yml —— 请在仓库根目录运行本脚本"
  exit 1
fi

# .env 是向导的记录文件，不进版本库（幂等追加）
grep -qE '^\.env$' .gitignore 2>/dev/null || printf '\n# 向导记录文件（值都在配置文件里，无需入库）\n.env\n' >> .gitignore

# ── Stage 1 · 确认用户名并替换 url 占位符 ─────────────────────────────────
stage "确认 GitHub 用户名"
say "博客仓库必须叫 <用户名>.github.io 才能拿到根路径站点（ADR-0002）。"
GIT_SUGGEST=$(git config --get user.name || echo "")
if [[ -z "$(_existing GITHUB_USERNAME || true)" && -n "$GIT_SUGGEST" ]]; then
  note "git 身份是 ${GIT_SUGGEST}，若这就是你的 GitHub 用户名，直接回车采用。"
  ask GITHUB_USERNAME "GitHub 用户名（回车采用 ${GIT_SUGGEST}）："
  [[ -z "$GITHUB_USERNAME" ]] && GITHUB_USERNAME="$GIT_SUGGEST"
else
  ask GITHUB_USERNAME "GitHub 用户名："
fi
[[ -n "$GITHUB_USERNAME" ]] || { warn "用户名不能为空"; exit 1; }
write_env GITHUB_USERNAME "$GITHUB_USERNAME"

REPO_SLUG="${GITHUB_USERNAME}/${GITHUB_USERNAME}.github.io"
SITE_URL="https://${GITHUB_USERNAME}.github.io"

if grep -q 'yourusername' _config.yml; then
  sed -i "s|yourusername|${GITHUB_USERNAME}|g" _config.yml
  printf '  %s✓%s _config.yml 的 url 已替换为 %s\n' "$GREEN" "$RESET" "$SITE_URL/"
else
  note "_config.yml 里已无占位符（此前替换过），跳过。"
fi

# ── Stage 2 · 创建远程仓库 ────────────────────────────────────────────────
stage "创建 GitHub 仓库"
say "在浏览器里创建一个空仓库，名字必须是 ${GITHUB_USERNAME}.github.io。"
open_url "https://github.com/new?name=${GITHUB_USERNAME}.github.io&visibility=public"
step "Repository name 填：${GITHUB_USERNAME}.github.io（链接已预填，核对即可）"
step "选择 Public（Giscus 要求公开仓库，共识 #11）"
step "下面的 Add a README / .gitignore / license 全部不勾——必须是空仓库，本地已有完整历史"
step "点 Create repository"
pause "创建完成后按回车继续"

# ── Stage 3 · 设置 Pages 发布源 ───────────────────────────────────────────
stage "设置 Pages 发布源为 GitHub Actions"
say "不切换这项，Actions 跑完也发不出去（ADR-0002 的前置条件）。"
open_url "https://github.com/${REPO_SLUG}/settings/pages"
step "Build and deployment → Source 下拉框 → 选 GitHub Actions"
note "若下拉里暂时没有 GitHub Actions 选项，先做下一阶段 push，完成后回来再设。"
pause "设置完成后按回车继续"

# ── Stage 4 · 关联远程并首次 push ────────────────────────────────────────
stage "关联远程并首次 push"
say "本阶段会真实推送代码；首次 push 会弹出浏览器让你登录 GitHub 授权。"
if git remote get-url origin >/dev/null 2>&1; then
  note "origin 已存在：$(git remote get-url origin)"
else
  git remote add origin "https://github.com/${REPO_SLUG}.git"
  printf '  %s✓%s 已关联 origin → https://github.com/%s.git\n' "$GREEN" "$RESET" "$REPO_SLUG"
fi
if ! git push -u origin main; then
  warn "push 失败——多半是浏览器授权没完成或网络问题。"
  pause "处理好后按回车重试（或 Ctrl-C 退出，下次重跑本向导会从记忆里继续）"
  git push -u origin main
fi
note "push 完成。Actions 已自动触发部署；若 Stage 3 没设置成功，这次会跑红——属预期，下一阶段处理。"

# ── Stage 5 · 确认部署状态 ────────────────────────────────────────────────
stage "确认 Actions 部署全绿"
open_url "https://github.com/${REPO_SLUG}/actions"
step "最新一条 Deploy to GitHub Pages 的 build / deploy 两个 job 都是绿色"
step "若是红色：点进 run 看报错——Pages 未启用就去补 Stage 3，然后在 run 页面右上角 Re-run all jobs"
note "以后改完文章 push 都会自动走这条流水线（ADR-0002）。"
pause "确认部署完成后按回车继续（暂时红了也不阻塞 Giscus 配置）"

# ── Stage 6 · 开 Discussions + 装 giscus app ──────────────────────────────
stage "开启 Discussions 并安装 giscus app"
say "评论数据存在仓库 Discussions 里（共识 #4），两步前置。"
open_url "https://github.com/${REPO_SLUG}/settings"
step "Settings → General → Features → 勾选 Discussions"
open_url "https://github.com/apps/giscus/installations/new"
step "Install Access 选 Only select repositories → 选中 ${GITHUB_USERNAME}.github.io → Install"
pause "两步都完成后按回车继续"

# ── Stage 7 · 获取并回填 giscus 配置 ──────────────────────────────────────
stage "获取 giscus 参数并回填"
say "从 giscus 官网生成配置，复制两个 ID 回来。"
open_url "https://giscus.app/zh-CN"
step "仓库一栏填 ${REPO_SLUG}（页面会打勾验证 Discussions 与 app 已就绪，红色提示说明上一阶段没做完）"
step "页面 ↔ Discussions 映射选 pathname（文章 URL 与讨论一一对应）"
step "Discussion Category 选 Announcements（只有管理员能开帖，防垃圾评论）"
step "往下翻到「启用 giscus」代码块，复制 data-repo-id 和 data-category-id 的值"
ask GISCUS_REPO_ID "粘贴 data-repo-id："
ask GISCUS_CATEGORY_ID "粘贴 data-category-id："
[[ -n "$GISCUS_REPO_ID" && -n "$GISCUS_CATEGORY_ID" ]] || { warn "两个 ID 都不能为空"; exit 1; }
write_env GISCUS_REPO "$REPO_SLUG"
write_env GISCUS_REPO_ID "$GISCUS_REPO_ID"
write_env GISCUS_CATEGORY_ID "$GISCUS_CATEGORY_ID"

# 区段感知回填：只动 giscus: 块的三个值和 comments: 块的 use（配置里有多处同名键）
awk -v r="$REPO_SLUG" -v ri="$GISCUS_REPO_ID" -v ci="$GISCUS_CATEGORY_ID" '
  /^[A-Za-z_]+:/ { sec = $0 }
  sec == "giscus:" && /^  repo:/ && !d1 { print "  repo: " r; d1=1; next }
  sec == "giscus:" && /^  repo_id:/    { print "  repo_id: " ri; next }
  sec == "giscus:" && /^  category_id:/{ print "  category_id: " ci; next }
  sec == "comments:" && /^  use:/ && !d2 { print "  use: giscus"; d2=1; next }
  { print }
' _config.butterfly.yml > _config.butterfly.yml.tmp && mv _config.butterfly.yml.tmp _config.butterfly.yml
printf '  %s✓%s 已回填 _config.butterfly.yml（giscus 三项 + comments.use: giscus）\n' "$GREEN" "$RESET"

say "本地构建验证配置没写坏："
if npx hexo clean >/dev/null 2>&1 && npx hexo generate >/dev/null 2>&1; then
  printf '  %s✓%s hexo generate 通过\n' "$GREEN" "$RESET"
else
  warn "构建失败！请检查 _config.butterfly.yml 的 giscus 段落格式后重跑本向导。"
  exit 1
fi

# ── Stage 8 · 提交上线与终验 ──────────────────────────────────────────────
stage "提交上线与终验"
if confirm "把 Giscus 配置提交并 push 上线？"; then
  git add -A
  git commit -m "上线配置：替换站点 url、启用 Giscus 评论" >/dev/null
  git push
  printf '  %s✓%s 已提交并推送，等 Actions 跑完（约 1 分钟）\n' "$GREEN" "$RESET"
else
  warn "跳过提交——配置只在本地生效，稍后手动 git add/commit/push。"
fi
pause "等 Actions 全绿后按回车，打开站点做终验"
open_url "${SITE_URL}/"
step "首页能看到四篇文章（你好世界 + 三篇占位）"
step "导航栏 分类/标签/关于 都能点开"
step "右上搜索框输入「占位」能出结果（本地搜索，共识 #15）"
step "随便进一篇文章，底部出现 giscus 评论区，用 GitHub 账号发一条测试评论（共识 #4）"
step "页脚出现访问量数字（不蒜子，共识 #16；数字从零开始是正常的）"
say "全部通过即上线完成；评论测试帖可稍后在仓库 Discussions 里删除。"

finish
